Register page - Issue Solved
cittakshashila/frontend pull request #18
Opened 2024-02-11 11:37 UTC by RaviprasathKJ

### **This pull request solves the following changes**
* Fixes Issue - [17 ](https://github.com/cittakshashila/frontend/issues/17)

###  **Checklist**
- [x] Replaced the ul with input tag .
- [x] Used the useState in the input tag .
- [x] Made the input responsive .

ptal 🤞 @BharathSanjeeviT @MKMukeshkannan .

2024-02-11 11:53 UTC, RaviprasathKJ commented
Added the underline .

2024-02-11 12:32 UTC, MKMukeshkannan requested changes
- use zod for form validation
- react-hook-form for submission
- use from tag and button with type `submit`
- Btw, the current commit is have _build issues_, kindly fix it
<img width="1440" alt="Screenshot 2024-02-11 at 5 53 58 PM" src="https://github.com/cittakshashila/frontend/assets/119940345/2070e760-09ba-4c5d-88b2-1faa3afac105">

2024-02-11 12:32 UTC, MKMukeshkannan commented on src/app/register/page.tsx
> +              <div className="ml-5 text-xl md:text-2xl lg:text-3xl font-passport flex flex-col justify-around  gap-[1rem] sm:gap-[2.5rem] flex-start ">
- The page is a registration form, So kindly use form tag

2024-02-11 12:32 UTC, MKMukeshkannan commented on src/app/register/page.tsx
>  import TakshashilaText from "../../../public/takshashila-text-2024.svg";
- just `"/takshasila-text-2024.svg"` will import it from public folder.

2024-02-11 12:32 UTC, MKMukeshkannan commented on src/app/register/page.tsx
> +    const [name,setName] : string = useState("");
- I suggest you to use `Zod` for form validation and `react-hook-form` for form submission

2024-02-13 08:46 UTC, RaviprasathKJ commented
@MKMukeshkannan 
Can please reviee my code , I have done the changes that you have asked .

2024-02-16 04:51 UTC, closed without merging